### ISSUE TITLE
Create oportunity form

### ISSUE THREAD

**Issue by ialberquilla** [Libree/eth-newyork#5]
Clicking on 

![image](https://github.com/Libree/eth-newyork/assets/974720/0815b6f0-3ba8-435d-aa60-77f2df09e591)

Should open a form to create an opportunity with the fields:

Name: opportunity name
Type: Select [Grant, Loan]
Max amount: integer
Currency: a select with options [USDC, DAI]

**Comment by TCLIV** [comment]
Done: https://github.com/Libree/eth-newyork/pull/7
